### ISSUE TITLE
permessage-deflate tries to compress control frames

### ISSUE THREAD

**Issue by DoctorMcKay** [faye/permessage-deflate-node#6]
As per the RFC, control frames may not be compressed (and therefore may not have RSV1 set). I'm implementing websocket-extensions and permessage-deflate into my own WebSocket driver, and passing control frames to `processOutgoingMessage` is causing protocol violations as permessage-deflate is setting RSV1.

For now I'll need to avoid passing control frames to `processOutgoingMessage`, but it's not beyond reason that some future (or custom) extension will want to act on control frames, so I don't think this is an ideal solution.

**Comment by jcoglan** [comment]
websocket-extensions defines two data types: `Message` and `Frame`, per the documentation. `processOutgoingMessage()` only takes `Message` values, which represent complete text/binary messages, not individual frames, and so you shouldn't pass control frames to it.

I wonder if the code or documentation could make this clearer, e.g. throwing an error if it receives an object of the wrong type or with the wrong `opcode`.

Future extensions may certainly want to operate on frames (early webkit compression implementations for example) but since there are no use cases for this yet it's not implemented. (This is why extensions must have a `type` field with value `"permessage"`: it anticipates the need for other types in future and means existing extensions won't break when more methods are added.

**Comment by DoctorMcKay** [comment]
I see.

It wouldn't necessarily be a bad idea to go ahead and implement perframe types, no? Perhaps for people who are using WebSockets internally, who control both the client and server, and who want to implement their own custom extensions which might need to act on individual frames.

Also, a question. I know this isn't necessarily the right place to ask questions, but we're already here and I don't know of a better place to ask. Is it impossible currently to stream fragmented frames that are acted upon by an extension? In my driver, implementations have the option to either have the driver buffer fragmented frames internally, or to receive a `Stream` which emits `data` events as continuation frames come in. Since we aren't waiting for the entire message to pass the data back to the client, I can't exactly send these frames to websocket-extensions and so it can't be compressed.

**Comment by jcoglan** [comment]
> It wouldn't necessarily be a bad idea to go ahead and implement perframe types, no?

There are currently no standardised perframe extensions, so designing an API for them would be pure speculation at this point.

> Is it impossible currently to stream fragmented frames that are acted upon by an extension?

This module does not currently support `Message.data` being a stream, only a buffer. The `websocket-extensions` module does not interact with the `data` field, so in principle that could be implemented entirely in extensions themselves without support from the framework. However, there is significant complexity in `websocket-extensions` for managing extensions with asynchronous processing, and I'm not sure how streamed messages would interact with that. See: https://github.com/faye/websocket-extensions-node/tree/master/lib/pipeline

**Comment by jcoglan** [comment]
Can I close this issue? I'm not sure there's anything specific to act on for now, other than I would like to try supporting `Message.data` being a stream in future.

**Comment by DoctorMcKay** [comment]
Yes, that's fine.
